String host = params.host
String port = params.port

pipeline {
    agent any

    stages {
        stage('Ping') {
            steps {
                script {
                    echo 'Проверяю доступность хоста...'
                    Boolean result = sh (
                        script: "ping -q -c 1 ${host}",
                        returnStatus: true
                    ) == 0
                    echo "Результат шага ${result}"
                    if (result) {
                        echo 'Хост доступен'
                    } else {
                        currentBuild.result = 'ABORTED'
                        error 'Хост не доступен'
                    }
                }
            }
        }
        stage('Port') {
            steps {
                script {
                    echo 'Проверяю доступность порта...'
                    String result = sh (
                        script: "nmap ${host} -p ${port} | grep -E 'Nmap\\sscan\\sreport\\sfor.+|^[0-9]+/[a-z]+.+|^\$'",
                        returnStdout: true
                    ).trim()
                    echo "Результат шага \n${result}"
                    if (result) {
                        echo 'Порт доступен'
                    } else {
                        currentBuild.result = 'ABORTED'
                        error 'Порт не доступен'
                    }
                }
            }
        }
    }
}